# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-SWIT
version:      0.06
version_from: lib/Apache/SWIT.pm
installdirs:  site
requires:
    Apache::Cookie:                
    Apache::Request:               
    Apache::Test:                  
    Class::Accessor:               
    Class::DBI:                    
    Class::Singleton:              
    DBIx::VersionedSchema:         
    ExtUtils::ModuleMaker:         
    HTML::Tested:                  
    Template:                      
    Test::Simple:                  0.44
    Test::TempDatabase:            
    WWW::Mechanize:                
    YAML:                          

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
