--- #YAML:1.0
name:                Apache-SWIT
version:             0.47
abstract:            mod_perl server with integrated testing
license:             ~
author:              
    - Boris Sukholitko (boriss@gmail.com)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache2::Cookie:               
    Apache2::Request:              
    Apache::DB:                    
    Apache::Test:                  
    Class::Accessor:               
    Class::DBI:                    
    Class::DBI::Pg:                0.09
    Class::DBI::Pg::More:          0.04
    DBD::Pg:                       2.11
    DBIx::VersionedSchema:         0.03
    Devel::NYTProf:                
    ExtUtils::ModuleMaker:         
    File::Slurp:                   
    HTML::Tested:                  0.48
    HTML::Tested::ClassDBI:        0.21
    HTML::Tested::JavaScript:      0.13
    IO::CaptureOutput:             
    IPC::Run:                      
    Linux::Smaps:                  
    Package::Alias:                
    Queue::Worker:                 
    Template:                      
    Test::Simple:                  0.44
    Test::TempDatabase:            0.13
    WWW::Mechanize:                
    YAML:                          
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
