# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-SWIT
version:      0.16
version_from: lib/Apache/SWIT.pm
installdirs:  site
requires:
    Apache::Cookie:                
    Apache::Request:               
    Apache::Test:                  
    Class::Accessor:               
    Class::DBI:                    
    Class::DBI::Pg:                
    DBIx::VersionedSchema:         
    ExtUtils::ModuleMaker:         
    File::Slurp:                   
    HTML::Tested:                  0.17
    HTML::Tested::ClassDBI:        0.06
    IPC::Run:                      
    Template:                      
    Test::Simple:                  0.44
    Test::TempDatabase:            
    WWW::Mechanize:                
    YAML:                          

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
