# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-SWIT
version:      0.42
version_from: lib/Apache/SWIT.pm
installdirs:  site
requires:
    Apache2::Cookie:               
    Apache2::Request:              
    Apache::DB:                    
    Apache::Test:                  
    Class::Accessor:               
    Class::DBI:                    
    Class::DBI::Pg:                0.09
    Class::DBI::Pg::More:          0.04
    DBIx::VersionedSchema:         0.03
    ExtUtils::ModuleMaker:         
    File::Slurp:                   
    HTML::Tested:                  0.46
    HTML::Tested::ClassDBI:        0.21
    HTML::Tested::JavaScript:      0.13
    IO::CaptureOutput:             
    IPC::Run:                      
    Package::Alias:                
    Queue::Worker:                 
    Template:                      
    Test::Simple:                  0.44
    Test::TempDatabase:            0.13
    WWW::Mechanize:                
    YAML:                          

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
